### ISSUE TITLE
Make it work with the latest LIFX firmware 2.0

### ISSUE THREAD

**Issue by brutella** [brutella/hklifx#1]

**Comment by brutevinch** [comment]
Any news about work with the latest LIFX firmware 2.0?

**Comment by brutella** [comment]
Not yet. Switching to [golifx](https://github.com/pdf/golifx) looks promising.

**Comment by brutevinch** [comment]
Hi!! How can get invite for home app? 😀

Отправлено с iPhone

**Comment by brutella** [comment]
Please get in touch via email

**Comment by brutevinch** [comment]
Sorry for misunderstood.... But this is already email?!))

Отправлено с iPhone

**Comment by brutella** [comment]
Personal email - see at the bottom of the website http://selfcoded.com/homecontrol/

**Comment by marckohlbrugge** [comment]
:+1: for a 2.0 fix. Just bought your Home app to help support development :)

**Comment by its-joshy** [comment]
👌🏽 excited for the 2.0 update!

**Comment by brutella** [comment]
This is now fixed with #2
