### ISSUE TITLE
Homekit devices not found in Homekit app

### ISSUE THREAD

**Issue by reefbarman** [brutella/hklifx#10]
Hi,

I'm running hklifxd and when searching for devices in a homekit app nothing is found. I have ensured that the daemon is allowed through the firewall etc etc.

I get the below output which is a little worrying

2016/01/13 18:32:46 [INFO] Discovered Location Our Home
2016/01/13 18:32:46 [INFO] Discovered Group Our Room
2016/01/13 18:32:48 [INFO] Discovered Device Zoe's Side
2016/01/13 18:32:48 [INFO] Creating New HKLight for Zoe's Side
2016/01/13 18:32:48 [INFO] Discovered Device Tristan's Side
2016/01/13 18:32:48 [INFO] Creating New HKLight for Tristan's Side
2016/01/13 18:32:48 [INFO] Accessory IP is 192.168.1.87
2016/01/13 18:32:48 [INFO] Accessory IP is 192.168.1.87
2016/01/13 18:32:48 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2016/01/13 18:32:48 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:45 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:45 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:45 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:45 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:45 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:45 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:45 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:45 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:46 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:46 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:46 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:33:46 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:15 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:16 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:16 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:16 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:16 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:16 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:16 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:16 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/13 18:34:16 [INFO] Unknown Device Event: shared.EventBroadcastSent

Any ideas?

**Comment by brutella** [comment]
> I'm running hklifxd and when searching for devices in a homekit app nothing is found I have ensured that the daemon is allowed through the firewall etc
> 
> Download the Bonjour Browser [1](https://itunes.apple.com/us/app/discovery-bonjour-browser/id305441017?mt=8) and check if you find entries under _hap._tcp service type.

–Matthias

**Comment by reefbarman** [comment]
Thanks for the reply, I'm running this on Windows (sorry I forgot to mention) could that be an issue?

**Comment by brutella** [comment]
I've switched to a different bonjour library last year.
This issue should be resolved by now.
