### ISSUE TITLE
hklifx does not recognize Color 1000 BR30

### ISSUE THREAD

**Issue by bacampbe** [brutella/hklifx#11]
hklifx does not seem to recognize the LIFX Color 1000 BR30 size bulb. The log prints the name of the bulb, but then says "Unsupported Device".

**Comment by bacampbe** [comment]
I'm guessing that the BR30 size bulb presents the same interface as  the A19 bulb. I suspect this is just a matter of adding an identifier to a list somewhere. I haven't found that location in the code so far; any pointers?

**Comment by brutella** [comment]
Should be fixed now
