### ISSUE TITLE
Communication error.

### ISSUE THREAD

**Issue by tregusti** [brutella/hklifx#16]
I have a similar problem as in #5 and #8, or maybe just need some clarification.

I run the daemon with the `-pin` argument, and I want to control my LIFX lamps that are already paired with the LIFX app since before.

In the Home app when trying to add the lamps, i get this warning "This accessory is not certified and may not work reliably with Homekit", I tap "Add anyway", and then I just get an error with "Error Network or other communication failure occurred". And at the same time in the daemon console I see "Close connection and remove session".

What is the specified pin needed for? Is that a later step? Why can't I communicate with the lamps? No errors show up in the log.

```
% go run hklifxd.go -pin 00102003 -v
2016/05/19 09:31:40 [INFO] Discovered Location Hemma
2016/05/19 09:31:40 [INFO] Discovered Group Kök
2016/05/19 09:31:40 [INFO] Discovered Device Kök salong
2016/05/19 09:31:40 [INFO] Creating New HKLight for Kök salong
2016/05/19 09:31:40 [INFO] Discovered Device Kök fönster
2016/05/19 09:31:40 [INFO] Creating New HKLight for Kök fönster
2016/05/19 09:31:41 [INFO] Accessory IP is 10.0.1.7
2016/05/19 09:31:41 [INFO] Accessory IP is 10.0.1.7
2016/05/19 09:31:42 [INFO] Close connection and remove session
2016/05/19 09:31:44 [INFO] Close connection and remove session
```

And thank you for creating this tool! I really hope I can get this to work. Finally Siri will be able to do something for me.

**Comment by brutella** [comment]
Please do the following steps
- Run the LIFX HomeKit bridge
- Download and run [Bonjour Browser](http://www.tildesoft.com)
- Post a screenshot of the entries under __hap._tcp_

**Comment by tregusti** [comment]
![image](https://cloud.githubusercontent.com/assets/1891942/15387301/b3d0a538-1dac-11e6-89e0-440a300b731f.png)

**Comment by brutella** [comment]
Please try to remove the "ö" character by renaming a light using the LIFX app and try again.

**Comment by tregusti** [comment]
Ahh, before I only had the "Kök xxx" lamps on, they still don't work. But the "Badrum" lamp asks for a pin now.

**Comment by tregusti** [comment]
And now after renaming one with a ö in it and restarting the server I get the same error again for all lamps. But they show up renamed everywhere.

EDIT: Restarted Home app and now I can add the lamps without ö.

So I guess there's the problem right there. No ö in the names. Not UTF8 through the whole system?

I'm off for now, back later

**Comment by tregusti** [comment]
Closed? I want to be able to use my native language for the lamp names.

**Comment by brutella** [comment]
I've created an issue in the hc library, where this has to be fixed

**Comment by tregusti** [comment]
Oh, sorry, thank you for the quick handling!
