### ISSUE TITLE
Update golifx to v0.5.1

### ISSUE THREAD

**Issue by pdf** [brutella/hklifx#18]
I just fixed a raft of bugs, particularly groups/locations were not in good shape, plus a couple of other races.  Should be a lot more consistent now.

**Comment by pdf** [comment]
v0.5.1 cleans up memory storage and improves reliability.

**Comment by broglea** [comment]
@pdf what all is entailed in this upgrade? Are there API changes or how does that process work? I am having some issues with my bulbs and hklifx and I am hoping doing this update will fix them. I would own that if it may help I'm just unclear what all needs to be done.

**Comment by pdf** [comment]
@broglea if you're building the project from source, you can `go get -u github.com/pdf/golifx` and then rebuild. I don't believe there should be any breaking changes from the client API, but if the project is using any internals there may be one or two issues.

**Comment by broglea** [comment]
@pdf that fixed my issue #19. I am going to comment on that with this solution and probably close that out then.

**Comment by pdf** [comment]
@broglea if you built with no problems, then there is nothing to do for golifx 0.5.1 compat.  I've suggested adopting dependency version management in #21, which is pretty much the only way to ensure users get the right build result if the project doesn't provide binaries.  Closing this out in favour of that issue.
