### ISSUE TITLE
Failed to initiliaze the client:

### ISSUE THREAD

**Issue by stevelucky** [brutella/hklifx#20]
When trying to run:

go run hklifxd.go -pin 00102003 -v

I'm getting:

Failed to initiliaze the client: listen udp4 :56700: bind: address already in use
exit status 1

I have no clue what this means.

**Comment by brutella** [comment]
Make sure that no other instance of the program is already running (and you forgot to quit).

**Comment by stevelucky** [comment]
I'm looking through Activity Monitor and don't see anything. What would it be called? Is there some other way to tell if two instances are running?

**Comment by brutella** [comment]
The process is called `hklifxd`
