### ISSUE TITLE
When trying to run go run hklifxd.go -pin 00102003 -v i get this error

### ISSUE THREAD

**Issue by NikolaiBain** [brutella/hklifx#26]
Not sure if this is a problem or i'm just doing it wrong, but this is what i get when i run 
"go run hklifxd.go -pin 00102003 -v" i get all of this:

vendor/github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:6:2: cannot find package "github.com/aead/chacha20" in any of:
    /Users/(_my name_)/go/src/vendor/github.com/brutella/hc/vendor/github.com/aead/chacha20 (vendor tree)
    /Users/(_my name_)/go/src/vendor/github.com/aead/chacha20
    /usr/local/go/src/github.com/aead/chacha20 (from $GOROOT)
    /Users/(_my name_)/go/src/github.com/aead/chacha20 (from $GOPATH)

vendor/github.com/pdf/golifx/protocol/v2/packet/packet.go:15:2: cannot find package "github.com/lunixbochs/struc" in any of:
    /Users/(_my name_)/go/src/vendor/github.com/lunixbochs/struc (vendor tree)
    /usr/local/go/src/github.com/lunixbochs/struc (from $GOROOT)
    /Users/(_my name_)/go/src/github.com/lunixbochs/struc (from $GOPATH)

github.com/brutella/hc/vendor/github.com/oleksandr/bonjour/client.go:10:2: cannot find package "github.com/miekg/dns" in any of:
    /Users/(_my name_)/go/src/github.com/brutella/hc/vendor/github.com/miekg/dns (vendor tree)
    /Users/(_my name_)/go/src/vendor/github.com/miekg/dns
    /usr/local/go/src/github.com/miekg/dns (from $GOROOT)
    /Users/(_my name_)/go/src/github.com/miekg/dns (from $GOPATH)

vendor/github.com/pdf/golifx/common/subscription.go:7:2: cannot find package "github.com/satori/go.uuid" in any of:
    /Users/(_my name_)/go/src/vendor/github.com/satori/go.uuid (vendor tree)
    /usr/local/go/src/github.com/satori/go.uuid (from $GOROOT)
    /Users/(_my name_)/go/src/github.com/satori/go.uuid (from $GOPATH)

vendor/github.com/brutella/hc/crypto/curve25519/curve25519.go:5:2: cannot find package "golang.org/x/crypto/curve25519" in any of:
    /Users/(_my name_)/go/src/vendor/github.com/brutella/hc/vendor/golang.org/x/crypto/curve25519 (vendor tree)
    /Users/(_my name_)/go/src/vendor/golang.org/x/crypto/curve25519
    /usr/local/go/src/golang.org/x/crypto/curve25519 (from $GOROOT)
    /Users/(_my name_)/go/src/golang.org/x/crypto/curve25519 (from $GOPATH)

vendor/github.com/brutella/hc/crypto/hkdf/hkdf.go:5:2: cannot find package "golang.org/x/crypto/hkdf" in any of:
    /Users/(_my name_)/go/src/vendor/github.com/brutella/hc/vendor/golang.org/x/crypto/hkdf (vendor tree)
    /Users/(_my name_)/go/src/vendor/golang.org/x/crypto/hkdf
    /usr/local/go/src/golang.org/x/crypto/hkdf (from $GOROOT)
    /Users/(_my name_)/go/src/golang.org/x/crypto/hkdf (from $GOPATH)

github.com/brutella/hc/vendor/github.com/oleksandr/bonjour/client.go:11:2: cannot find package "golang.org/x/net/ipv4" in any of:
    /Users/(_my name_)/go/src/github.com/brutella/hc/vendor/golang.org/x/net/ipv4 (vendor tree)
    /Users/(_my name_)/go/src/vendor/golang.org/x/net/ipv4
    /usr/local/go/src/golang.org/x/net/ipv4 (from $GOROOT)
    /Users/(_my name_)/go/src/golang.org/x/net/ipv4 (from $GOPATH)

github.com/brutella/hc/vendor/github.com/oleksandr/bonjour/client.go:12:2: cannot find package "golang.org/x/net/ipv6" in any of:
    /Users/(_my name_)/go/src/github.com/brutella/hc/vendor/golang.org/x/net/ipv6 (vendor tree)
    /Users/(_my name_)/go/src/vendor/golang.org/x/net/ipv6
    /usr/local/go/src/golang.org/x/net/ipv6 (from $GOROOT)
    /Users/(_my name_)/go/src/golang.org/x/net/ipv6 (from $GOPATH)

What am i doing wrong?

**Comment by bradfeehan** [comment]
I had this, I think `go get` was what fixed it for me.

**Comment by NikolaiBain** [comment]
When exactly do i put this command?

**Comment by NikolaiBain** [comment]
Huh, figured it out and yup that did fix it, thank you!!!
