### ISSUE TITLE
Newest "Generation 3" LIFX bulb seen as "Unsupported Device"

### ISSUE THREAD

**Issue by bland328** [brutella/hklifx#29]
Though two older "Color 1000" bulbs are still working fine, an "All New Generation 3" LIFX bulb I purchased recently is seen as an "Unsupported Device."

In the LIFX app, the new, unsupported bulb model is listed as "LIFX (A19) v 2.9", whereas the older, compatible bulb model is listed as "LIFX Color 1000 v 1.20".

Here are two links to the unsupported bulb:
http://www.lifx.com/products/lifx?variant=30732331715
https://www.amazon.com/gp/product/B01KY02MS8

**Comment by brutella** [comment]
I've updated to the latest version of [golifx]() (which handles the LIFX protocol) with commit 9b518e6f665d2c7e492ff724522f77ef76fc177e. Please pull those changes from `master` and try again.

**Comment by bland328** [comment]
Thanks, @brutella! That fixed everything right up.

Very impressive, and I certainly appreciate the time and effort that've gone into hklifx--my household benefits from it a dozen times a day.
