### ISSUE TITLE
Doesn't work with my lifx.

### ISSUE THREAD

**Issue by brutevinch** [brutella/hklifx#3]
All info and screenshots done at same time. No troubles in network. No Packet Drops. LIFX app works well.
Accessory after ~20 sec just gone but ping to light bulb is stable.

64 bytes from 10.0.1.120: icmp_seq=1 ttl=128 time=5.981 ms
64 bytes from 10.0.1.120: icmp_seq=2 ttl=128 time=5.803 ms
64 bytes from 10.0.1.120: icmp_seq=3 ttl=128 time=7.072 ms
64 bytes from 10.0.1.120: icmp_seq=4 ttl=128 time=6.565 ms
64 bytes from 10.0.1.120: icmp_seq=5 ttl=128 time=5.946 ms
64 bytes from 10.0.1.120: icmp_seq=6 ttl=128 time=6.022 ms
64 bytes from 10.0.1.120: icmp_seq=7 ttl=128 time=7.011 ms
64 bytes from 10.0.1.120: icmp_seq=8 ttl=128 time=7.153 ms
64 bytes from 10.0.1.120: icmp_seq=9 ttl=128 time=7.387 ms
64 bytes from 10.0.1.120: icmp_seq=10 ttl=128 time=8.937 ms
64 bytes from 10.0.1.120: icmp_seq=11 ttl=128 time=5.794 ms
64 bytes from 10.0.1.120: icmp_seq=12 ttl=128 time=6.440 ms
64 bytes from 10.0.1.120: icmp_seq=13 ttl=128 time=6.133 ms
64 bytes from 10.0.1.120: icmp_seq=14 ttl=128 time=6.921 ms
64 bytes from 10.0.1.120: icmp_seq=15 ttl=128 time=3.575 ms
64 bytes from 10.0.1.120: icmp_seq=16 ttl=128 time=6.579 ms
64 bytes from 10.0.1.120: icmp_seq=17 ttl=128 time=4.665 ms
64 bytes from 10.0.1.120: icmp_seq=18 ttl=128 time=7.084 ms

![2015-11-01 2 04 27](https://cloud.githubusercontent.com/assets/12526597/10865879/1585de50-803d-11e5-92d0-e19b4c0595d5.png)

![img_0161](https://cloud.githubusercontent.com/assets/12526597/10865876/0877782c-803d-11e5-95a6-5a8f7adb775a.PNG)

**Comment by brutevinch** [comment]
Maybe it helps : https://github.com/mclarkk/lifxlan  this project works perfectly but it's only cli to lifx. (((

**Comment by brutella** [comment]
30 seconds after the bridge loses the connection to the LIFX bulb, the virtual light bulb is set to unreachable. Try to pull the plug from the LIFX bulb and then turn it back on. The bridge should automatically find the bulb and make it reachable to HomeKit again.

**Comment by brutevinch** [comment]
Re-plug doesn't help. Accessory unreachable. Any advice how to fix your app? I can't understand why all other works fine except hklifx =(((

**Comment by brutella** [comment]
Try to run the program with the `-v` option and post the output here.

`go run hklifxd.go -pin 13572460 -v`

**Comment by brutella** [comment]
Also, if you rename the LIFX bulb in the official LIFX app, you have to repair it in the Home app.

**Comment by brutevinch** [comment]
Maybe rename.... today test it. Thx

**Comment by brutevinch** [comment]
No, same sad thing.

2015/11/01 19:31:55 [VERB] 10.0.1.6:49450 GET /characteristics
2015/11/01 19:31:55 [VERB] 10.0.1.6:49450 GET /characteristics
2015/11/01 19:31:55 [VERB] 10.0.1.6:49450 GET /characteristics
2015/11/01 19:31:55 [VERB] 10.0.1.6:49450 GET /characteristics
2015/11/01 19:32:06 [VERB] 10.0.1.6:49450 PUT /characteristics
2015/11/01 19:32:06 [VERB] {"characteristics":[{"aid":1,"iid":10,"value":70}]}
2015/11/01 19:32:06 [INFO] Changed Brightness for Ночник to 70
2015/11/01 19:32:06 [INFO] Updated Color for Ночник
2015/11/01 19:32:06 [VERB] 10.0.1.6:49450 <- EVENT/1.0 200 OK
Content-Length: 51
Content-Type: application/hap+json

{"characteristics":[{"aid":1,"iid":10,"value":69}]}
2015/11/01 19:32:10 [VERB] 10.0.1.6:49450 PUT /characteristics
2015/11/01 19:32:10 [VERB] {"characteristics":[{"aid":1,"iid":10,"value":54}]}
2015/11/01 19:32:10 [INFO] Changed Brightness for Ночник to 54
2015/11/01 19:32:10 [INFO] Updated Color for Ночник
2015/11/01 19:32:10 [VERB] 10.0.1.6:49450 <- EVENT/1.0 200 OK
Content-Length: 51
Content-Type: application/hap+json

{"characteristics":[{"aid":1,"iid":10,"value":53}]}
2015/11/01 19:32:21 [VERB] 10.0.1.6:49450 GET /characteristics
2015/11/01 19:32:36 [VERB] 10.0.1.6:49450 GET /characteristics
2015/11/01 19:36:34 [INFO] Close connection and remove session

**Comment by brutella** [comment]
I don't see any errors in your logs. iOS automatically closes a connection sometimes – that's intended behavior.

**Comment by brutella** [comment]
Related to https://github.com/brutella/hc/issues/31

**Comment by brutella** [comment]
Closed due to inactivity.
