### ISSUE TITLE
Can't start the program

### ISSUE THREAD

**Issue by cooperbow88** [brutella/hklifx#30]
When ever I try to start the program or run go get I get
 hklifx/vendor/github.com/brutella/hc/crypto/chacha20poly1305
vendor\github.com\brutella\hc\crypto\chacha20poly1305\chacha20_poly1305.go:28: undefined: chacha20.NewChaCha20Poly1305
vendor\github.com\brutella\hc\crypto\chacha20poly1305\chacha20_poly1305.go:29: not enough arguments to return
        have (<T>)
        want ([]byte, error)
vendor\github.com\brutella\hc\crypto\chacha20poly1305\chacha20_poly1305.go:35: undefined: chacha20.TagSize
vendor\github.com\brutella\hc\crypto\chacha20poly1305\chacha20_poly1305.go:35: invalid array bound chacha20.TagSize
vendor\github.com\brutella\hc\crypto\chacha20poly1305\chacha20_poly1305.go:46: undefined: chacha20.TagSize
vendor\github.com\brutella\hc\crypto\chacha20poly1305\chacha20_poly1305.go:51: undefined: chacha20.NewChaCha20Poly1305

**Comment by brutella** [comment]
Fixed with 24be0ae
