### ISSUE TITLE
UUID API broken - satori/go.uuid

### ISSUE THREAD

**Issue by s-clarke** [brutella/hklifx#37]
## Nature of the Issue
I recieved the following error when attempting to get hklifx up and running

`# hklifxd/vendor/github.com/pdf/golifx/common/vendor/github.com/pdf/golifx/common/subscription.go:69:23: multiple-value uuid.NewV4() in single-value context`

## Probable Cause 
It appears to relate to [Issue #66 in satori/go.uuid](https://github.com/satori/go.uuid/issues/66) where an update to that project has caused things to break. Several other projects seem to have identified similar issues. 

## Quick and Dirty resolution
If you've found this post while troubleshooting the error and just want to get hklifx up and running - I managed to get it working by  editing the `subscription.go` file and replacing 

`github.com/satori/go.uuid` with `github.com/rkuris/go.uuid`

**Comment by brutella** [comment]
hklifx now uses Go modules, which should resolve this issue.
