### ISSUE TITLE
LIFX bulbs get detected and I see in "home" app but then I can't add in "Home" app

### ISSUE THREAD

**Issue by thedeftt** [brutella/hklifx#5]
Trying to get my LIFX bulbs configured into the "Home" app I purchased from you, here's what happens:

C:\Program Files\Git>cd c:\work\src\hklifx

c:\work\src\hklifx>go run hklifxd.go -pin 00102003 -v
2015/11/06 14:31:27 [INFO] Discovered Location Home
2015/11/06 14:31:27 [INFO] Discovered Group Bedroom
2015/11/06 14:31:27 [INFO] Discovered Device LIFX #5
2015/11/06 14:31:27 [INFO] Creating New HKLight for LIFX #5
2015/11/06 14:31:27 [INFO] Discovered Device LIFX #4
2015/11/06 14:31:27 [INFO] Creating New HKLight for LIFX #4
2015/11/06 14:31:27 [INFO] Discovered Device LIFX #7
2015/11/06 14:31:27 [INFO] Creating New HKLight for LIFX #7
2015/11/06 14:31:27 [INFO] Discovered Device LIFX #2
2015/11/06 14:31:27 [INFO] Discovered Device LIFX #8
2015/11/06 14:31:27 [INFO] Discovered Device LIFX #3
2015/11/06 14:31:27 [INFO] Discovered Device LIFX #1
2015/11/06 14:31:27 [INFO] Creating New HKLight for LIFX #1
2015/11/06 14:31:27 [INFO] Creating New HKLight for LIFX #2
2015/11/06 14:31:27 [INFO] Creating New HKLight for LIFX #8
2015/11/06 14:31:27 [INFO] Creating New HKLight for LIFX #3
2015/11/06 14:31:27 [INFO] Accessory IP is 169.254.109.143
2015/11/06 14:31:27 [INFO] Accessory IP is 169.254.109.143
2015/11/06 14:31:27 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/06 14:31:27 [INFO] Accessory IP is 169.254.109.143
2015/11/06 14:31:27 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/06 14:31:27 [INFO] Accessory IP is 169.254.109.143
2015/11/06 14:31:27 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/06 14:31:27 [INFO] Accessory IP is 169.254.109.143
2015/11/06 14:31:27 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/06 14:31:27 [INFO] Accessory IP is 169.254.109.143
2015/11/06 14:31:27 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/06 14:31:27 [INFO] Accessory IP is 169.254.109.143
2015/11/06 14:31:27 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/06 14:31:57 [INFO] Unknown Device Event: shared.EventBroadcastSent

**Comment by brutella** [comment]
The errors means that your mDNS records (bonjour) are not available on IPv6 – over IPv4 they still be available though.

**Comment by thedeftt** [comment]
I wouldn't know where to start with resolving this, any chance I can get you to point me in the right direction? No worries if not, I'm sure you're working on a lot

**Comment by brutella** [comment]
Can you pair your light bulbs in the Home app?
You have to into a home, then tap + to see a list of all unpaired accessories.

**Comment by thedeftt** [comment]
I'm unable to successfully pair them in the Home app. When I run hklifx it initially discovers them and I can see them in the Home app after I tap + but when I attempt to add them something goes wrong and very shortly after will disappear from the list of unpaired accessories but still not be added to my HomeKit group in the "Home" app

**Comment by brutella** [comment]
When you try to pair the light bulb, does a view appear where you can enter a pin?
Do you see any errors in the log for hklifx after you tried to pair it in the Home app?

**Comment by thedeftt** [comment]
When I try to pair the light bulb it does not appear where I can enter a pin. When I try to pair by tapping the bulb in the Home app it first says "Add HomeKit Accessory" "This accessory is not certified and may not work reliably with Homekit" then I tap "Add anyway" and after that nothing happens for a few seconds and then the Home app gives "Error Network or other communication failure occurred."

Meanwhile this is whatthe log for hklifx is doing:
C:\Program Files\Git>cd c:\work\src\hklifx

c:\work\src\hklifx>goget
'goget' is not recognized as an internal or external command,
operable program or batch file.

c:\work\src\hklifx>go get
go install: no install location for directory c:\work\src\hklifx outside GOPATH
        For more details see: go help gopath

c:\work\src\hklifx>go run hklifxd.go -pin 00102003 -v
2015/11/08 04:49:06 [INFO] Discovered Location Home
2015/11/08 04:49:06 [INFO] Discovered Group Bedroom
2015/11/08 04:49:06 [INFO] Discovered Device LIFX #3
2015/11/08 04:49:06 [INFO] Creating New HKLight for LIFX #3
2015/11/08 04:49:06 [INFO] Discovered Device LIFX #4
2015/11/08 04:49:06 [INFO] Creating New HKLight for LIFX #4
2015/11/08 04:49:06 [INFO] Discovered Device LIFX #8
2015/11/08 04:49:06 [INFO] Creating New HKLight for LIFX #8
2015/11/08 04:49:06 [INFO] Discovered Device LIFX #2
2015/11/08 04:49:06 [INFO] Creating New HKLight for LIFX #2
2015/11/08 04:49:06 [INFO] Discovered Device LIFX #1
2015/11/08 04:49:06 [INFO] Creating New HKLight for LIFX #1
2015/11/08 04:49:06 [INFO] Discovered Device LIFX #5
2015/11/08 04:49:06 [INFO] Creating New HKLight for LIFX #5
2015/11/08 04:49:06 [INFO] Discovered Device LIFX #7
2015/11/08 04:49:06 [INFO] Creating New HKLight for LIFX #7
2015/11/08 04:49:06 [INFO] Accessory IP is 169.254.109.143
2015/11/08 04:49:06 [INFO] Accessory IP is 169.254.109.143
2015/11/08 04:49:06 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/08 04:49:06 [INFO] Accessory IP is 169.254.109.143
2015/11/08 04:49:06 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/08 04:49:06 [INFO] Accessory IP is 169.254.109.143
2015/11/08 04:49:06 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/08 04:49:06 [INFO] Accessory IP is 169.254.109.143
2015/11/08 04:49:06 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/08 04:49:06 [INFO] Accessory IP is 169.254.109.143
2015/11/08 04:49:06 [INFO] Accessory IP is 169.254.109.143
2015/11/08 04:49:06 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/08 04:49:06 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :535
3: bind: Only one usage of each socket address (protocol/network address/port) i
s normally permitted.
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:49:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:09 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:09 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:09 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:09 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:09 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:09 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:09 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:50:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:51:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:52:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:53:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:06 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent
2015/11/08 04:54:36 [INFO] Unknown Device Event: shared.EventBroadcastSent

**Comment by brutella** [comment]
I can't see any error related to the bridge.
Please restart your iOS device and try again.

**Comment by John-K** [comment]
I am in this exact situation as well, iPhone6S+ iOS 9.1 (13B143)

**Comment by John-K** [comment]
After restarting Home and the hklifxd, I saw a list of bulbs and was able to manually pair with one, although pairing with the other two seems to have hung, Home gives "Error: Operation in progress."

It seems restarting both Home and hklifxd allows pairing with one device, but one device only.

**Comment by petersteneteg** [comment]
Had very similar problems, but after restarting my iPhone and hklifxd it works perfectly!

**Comment by ashilp** [comment]
I also ran into similar issue. When I run the command, it is able to discover the device. It can even read the status of the device when I change the color of the bulb from lifx app. But when I try to add the accessory in home application, it gives me network error. As you can see below, it prompted for the pin once. But it disconnected immediately.

I tried to restart the daemon, Lifx bulb as well as the home application. It did not work for me. Are there some network settings I need to change from my side ?

C:\gocode\src\hklifx>go run hklifxd.go -pin 00102003 -v
2016/04/09 17:38:34 [INFO] Discovered Location Shilpa Santosh Home
2016/04/09 17:38:34 [INFO] Discovered Group Master Bedroom
2016/04/09 17:38:34 [INFO] Discovered Device LIFX bulb 12ab7f
2016/04/09 17:38:34 [INFO] Creating New HKLight for LIFX bulb 12ab7f
2016/04/09 17:38:34 [INFO] Accessory IP is 169.254.16.124
2016/04/09 17:38:34 [ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2016/04/09 17:39:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:32 [VERB] [2601:647:4e01:5616:aebc:32ff:fe87:6b6b]:52834 POST /pair-setup
2016/04/09 17:39:32 [VERB] Create new pair setup controller
2016/04/09 17:39:32 [VERB] <-     B: 521acbbd4a2127116c09394a218dde1aae6124ee0813a390584cefd3710e4460b85f2e183afe22f0bfa94e02bf771ab12ac5485a5bd35186881f58903ac04365a8d4639cf3bf9635f221f2df4b14c758b09712de610b575b21811f254cb8ef2baef7ffec76df3ab0de2592e59c955eaddab5368580d78f6423bc8b38726c50cd3ff78a7c571c5672985c86f064ba124e61983371036b9ed448640eba7ad75c725c49a6ffa3b54da64d2507c04efa928a993b65db3df52d891e82497c1ccbf3a6b371c8dbfd946908b582af2fc2981ae35746b6c4a23d1e66ac398b7089893a6ce4e9f26cc07164d93564fb9ccfb39c472da6063a207f5277c914fb44a184158325ad8d21ed2dbd65ce7ef44dd938e4b076d4e6d3552dcec57694b950d08ec56d71309376bdfb180cee9763862ef1596e6515b1bc65821b76bd2aac3119e9788a6781b2cbaab990f9559916a9f15d2d4553f25f7eb3bcc8386ec3d9d84367e8781681e9c87087d87f1c41cfe66e6378e17800b73c7fc756d17de79d8e28f09e69
2016/04/09 17:39:32 [VERB] <-     s: 51e08e88e4bb95f78e6725a543dddeab
2016/04/09 17:39:34 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:34 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:34 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:34 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:34 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:39:34 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:40:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:40:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:40:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:40:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:40:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:40:04 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:40:34 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:40:34 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/04/09 17:40:34 [INFO] Unknown Device Event: shared.EventBroadcastSent

**Comment by brutella** [comment]
This issue should be resolved with the latest changes.
