### ISSUE TITLE
How to Pair with iOS

### ISSUE THREAD

**Issue by samho1976** [brutella/hklifx#8]
Hi, your hklifx is simply awesome. I following exact untill the last part and stuck... could you help to enlighten me

Code below has to be run on OSX or ios?
go run hklifxd.go -pin 00102003 -v

the requirement --> -pin [8-digits] must be entered on iOS to pair with the light bulb(s). I couldnt access to my ios terminal as my iphone has not been jailbreak. Any workaround? 

Thanks in advance.

**Comment by liamnichols** [comment]
Once you've compiled hklifx, you then run that command on your computer to start the server/bridge.

You should then be able to use an app like Home on your iOS device to discover your bulbs.

Happy new year! 🎉

**Comment by samho1976** [comment]
Hi thanks. I can use my siri already. Thanks alot. Btw, i noticed that i need to leave my pc on. Else my siri will not work. 

Regards,
Sam Ho

**Comment by liamnichols** [comment]
Yep, you'd need a third party app to pair it and set it up but Siri works once that's been done.

Your computer needs to run because the hklifx is the bridge between your phone and bulbs, without it they can't communicate together

**Comment by brutella** [comment]
Not an issue related to the project.
