### ISSUE TITLE
Devices stop working after a few minutes

### ISSUE THREAD

**Issue by Lorkster** [brutella/hklifx#9]
Set up and start works as it should, but after a few minutes this appears in the log:

```
2016/01/03 12:44:24 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/03 12:44:24 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/03 12:44:24 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/03 12:44:24 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/03 12:44:24 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/03 12:44:24 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/03 12:44:24 [INFO] Unknown Device Event: shared.EventBroadcastSent
2016/01/03 12:44:33 [INFO] Close connection and remove session
2016/01/03 12:44:33 [INFO] Close connection and remove session
2016/01/03 12:44:33 [INFO] Close connection and remove session
2016/01/03 12:44:33 [INFO] Close connection and remove session
2016/01/03 12:44:33 [INFO] Close connection and remove session
2016/01/03 12:44:33 [INFO] Close connection and remove session
```

After this all the LIFX lights are marked as "Not Reachable" in the home app and hklifx needs to be restarded.

**Comment by Lorkster** [comment]
A small update. The only indication of a pattern, except time, is that as soon as my IOS device have been locked for 30 seconds (allowing hklifx one polling cycle, and I guess that would cause it to disconnect from WIFI and thus make the Home app lose connection) the devices turn "Not reachable" upon returning to the Home app and they never recover. In other words, it might as well be the Home app doing something strange, but I can't debug that. Sadly it makes the Home app completely unusable for me since the whole point was controlling LIFX bulbs.

**Comment by brutella** [comment]
I can assure that the Home app does nothing special. It only uses the HomeKit API on iOS. What the HomeKit daemon does in the background is out of my control.

**Comment by powermundsen** [comment]
I have the same problem, I'm thinking of running a script that automatically listens to the log and restarts hklifx. Unfortunately I'm not that good at this stuff yet, maybe one of you could point mein the right direction?

**Comment by lulezi** [comment]
I ran into this issue as well. It seems like the bulb disconnects from the hklifx daemon. `ctrl`+`c`ing the daemon and restarting it resolves the problem.

**Comment by brutella** [comment]
Related to https://github.com/brutella/hc/issues/31

**Comment by suntzu3x** [comment]
This is a silly question im sure. Everything works great until i close terminal.  Does terminal need to be running for this to work? Thanks and sorry if thats an obvious yes!

**Comment by brutella** [comment]
@suntzu3x Yes, the terminal keeps the program running.

**Comment by brutella** [comment]
This will be fixed in the future by updating the `hc` library to use another mDNS/DNSSD library. For now you can checkout the `golifx-dnssd` branch, which includes the new library version – see [#22](https://github.com/brutella/hklifx/issues/22#issuecomment-334406822).
